main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.kegiatan, name='kegiatan'),
    path('create_kegiatan/',views.createKegiatan, name='create_kegiatan'),
    path('tambah_peserta/',views.tambahPeserta, name='tambah_peserta'),
    path('output/',views.hasil, name='hasil'),
]

story6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.nama_kegiatan
    
class Peserta(models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
    nama_peserta = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.nama_peserta

main/forms.py
from django.forms import ModelForm
from .models import Kegiatan, Peserta

class KegiatanForm(ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'
        
class PesertaForm(ModelForm):
    class Meta:
        model = Peserta
        fields = '__all__'

main/views.py
from django.shortcuts import render,redirect 
from django.http import HttpResponse
from .forms import KegiatanForm, PesertaForm
from .models import Kegiatan , Peserta


def kegiatan(request):
    return render(request, 'main/kegiatan.html')

def createKegiatan(request):
    form = KegiatanForm()
    isi = {'form' : form}
    if request.method == "POST":
        form = KegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
            
    return render(request, 'main/kegiatan_form.html',isi)


def tambahPeserta(request):
    form = PesertaForm()
    isi = {'form' : form}
    if request.method == "POST":
        form = PesertaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
            
    return render(request, 'main/peserta_form.html',isi)

def hasil(request):
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all() 
    isi = {
            'Kegiatan' : kegiatan,
           'Peserta' : peserta,
           }
    if request.method == "POST":
        form = tambahPeserta(request.POST)
        if form.is_valid():
            return redirect('/')
            
    return render(request, 'main/output.html',isi)

main/templates/main/dashboard.html
{% extends 'base.html' %}

{% block content %}


<br>
	<div class="col-md-5">
		<h2>Kegiatan PEWE</h2>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'create_kegiatan' %}">Create Order</a>
			<table class="table table-sm">
				<tr>
					<th>Nama peserta</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>

				{% for peserta in Peserta %}
					<tr>
						<td>{{peserta.nama_peserta}}</td>
						<td><a class="btn btn-sm btn-info" href="{% url 'tambah_peserta' %}">Update</a></td>
						<td><a class="btn btn-sm btn-danger" href="{% url 'delete_peserta' peserta.id %}">Delete</a></td>

					</tr>
				{% endfor %}

		
			</table>
		</div>
	</div>

</div>

{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

main/templates/main/kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story6</title>
{% endblock meta %}

{% block content %}  
{% include 'navbar.html' %}
  <form action="" method="POST">
		{% csrf_token %}
		{{form.as_p}}			
		<input type="submit" name="Tambah peserta">
	</form>
{% endblock content %}

main/templates/main/kegiatan_form.html
{% include 'base.html' %}
{% load static %}

{% block meta %}
<title>addkegiatan Story6</title>
{% endblock meta %}

{% block content %}  
{% include 'navbar.html' %}
  <form action="" method="POST">
		{% csrf_token %}
		{{form}}			
		<input type="submit" name="Submit">
	</form>
{% endblock content %}

main/templates/main/output.html
{% include 'base.html' %}
{% load static %}
{% block meta %}
<title>output Story6</title>
{% endblock meta %}
{% block content %}
    {% include 'navbar.html' %}
	<div class="col-md-5">
		<h2>Kegiatan PEWE</h2>
		<hr>
    		<div class="kegiatan">
    			{% for kegiatan in Kegiatan %}
                    <div style= "width: 300px;border: 15px solid green;padding: 50px;margin: 20px;">
                    <p style= "text-align:center;">{{kegiatan.nama_kegiatan}}</p>
        			<ul>
        			{% for peserta in Peserta %}
                        <li>{{peserta.nama_peserta}}</li>
        			{% endfor %}
                    </ul>            
        		</div>
    			{% endfor %}
    		</div>
	</div>


{% endblock %}

main/templates/main/peserta_form.html
{% include 'base.html' %}
{% load static %}

{% block meta %}
<title>addpeserta Story6</title>
{% endblock meta %}

{% block content %}  
  <form action="" method="POST">
		{% csrf_token %}
		{{form}}			
		<input type="submit" name="Submit">
	</form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:create_kegiatan' %}">addKegiatan <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:hasil' %}">Daftar Kegiatan</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:tambah_peserta' %}">Tambah Peserta</a>
      </li>
    </ul>
  </div>
</nav>